name: Build Tatanako TDX IO Firmware

on:
  push:
    paths:
      - 'firmware/**'
      - '.github/workflows/build.yaml'
  pull_request:
    paths:
      - 'firmware/**'
      - '.github/workflows/build.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # 安装 Ninja、CMake 以及 ARM 交叉编译工具链
          sudo apt-get install -y ninja-build cmake build-essential gcc-arm-none-eabi

      - name: Build Firmware
        working-directory: firmware
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake .. -G Ninja -DPICO_SDK_FETCH_FROM_GIT=on
          ninja
          ls

      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdx_firmware
          path: src/tdx_firmware.uf2
          if-no-files-found: error
